Repository virtuelabs-io/rapido-web, pull requests merged in 2019-09, with the labels that each got.

#145 Added session generation for tracking user activity and for guest checkout
  package-lock.json
  package.json
  src/app/components/topnav/topnav.component.ts
  src/app/utils/constants.ts
Labels: enhancement

#146 Feature/test case address
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/components/add-address/add-address.component.html
  src/app/components/add-address/add-address.component.spec.ts
  src/app/components/add-address/add-address.component.ts
  src/app/components/address/address.component.spec.ts
  src/app/components/address/address.component.ts
  src/app/components/company-details/company-details.component.html
  src/app/components/company-details/company-details.component.spec.ts
  src/app/components/company-details/company-details.component.ts
  src/app/components/confirmation-dialog/confirmation-dialog.component.html
  src/app/components/confirmation-dialog/confirmation-dialog.component.scss
  src/app/components/confirmation-dialog/confirmation-dialog.component.spec.ts
  src/app/components/confirmation-dialog/confirmation-dialog.component.ts
  src/app/services/customer/company-details.mock.data.ts
  src/app/services/customer/company-details.mock.service.ts
  src/app/services/customer/company-details.service.ts
Labels: enhancement

#147 Feature/cart tests
  src/app/components/cart/cart.component.spec.ts
  src/app/components/cart/cart.component.ts
  src/app/services/cart/cart.mock.data.ts
  src/app/services/cart/cart.mock.service.ts
  src/app/services/cart/cart.service.ts
Labels: enhancement

#150 Feature/orders test
  src/app/app.component.ts
  src/app/components/account-info/account-info.component.html
  src/app/components/account-info/account-info.component.spec.ts
  src/app/components/account-info/account-info.component.ts
  src/app/components/add-address/add-address.component.spec.ts
  src/app/components/add-address/add-address.component.ts
  src/app/components/address/address.component.spec.ts
  src/app/components/address/address.component.ts
  src/app/components/card/carousel/carousel.component.spec.ts
  src/app/components/card/home-card/home-card.component.ts
  src/app/components/cart/cart.component.spec.ts
  src/app/components/cart/cart.component.ts
  src/app/components/checkout/checkout.component.spec.ts
  src/app/components/checkout/checkout.component.ts
  src/app/components/company-details/company-details.component.spec.ts
  src/app/components/company-details/company-details.component.ts
  src/app/components/edit-address/edit-address.component.spec.ts
  src/app/components/edit-address/edit-address.component.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.spec.ts
  src/app/components/footer/footer.component.ts
  src/app/components/home/home.component.ts
  src/app/components/log-in/log-in.component.spec.ts
  src/app/components/log-in/log-in.component.ts
  src/app/components/order-details/order-details.component.spec.ts
  src/app/components/order-details/order-details.component.ts
  src/app/components/orders/orders.component.spec.ts
  src/app/components/orders/orders.component.ts
  src/app/components/product-details/product-details.component.spec.ts
  src/app/components/product-results/product-results.component.ts
  src/app/components/register/register.component.spec.ts
  src/app/components/resend-otp/resend-otp.component.ts
  src/app/components/topnav/topnav.component.ts
  src/app/services/commons/rapido-http.service.ts
  src/app/services/orders/orders.mock.data.ts
  src/app/services/orders/orders.mock.service.ts
  src/app/services/orders/orders.service.ts
  src/app/services/products/products-hierarchy.service.ts
  src/app/services/products/products.service.ts
Labels: enhancement

#151 Feature/account test
  src/app/common/icons/icons.component.html
  src/app/components/account-info/account-info.component.html
  src/app/components/account-info/account-info.component.scss
  src/app/components/account-info/account-info.component.spec.ts
  src/app/components/account-info/account-info.component.ts
  src/app/components/career-page/career-page.component.html
  src/app/components/career-page/career-page.component.scss
  src/app/components/cart/cart.component.scss
  src/app/components/checkout/checkout.component.html
  src/app/components/checkout/checkout.component.scss
  src/app/components/checkout/checkout.component.spec.ts
  src/app/components/checkout/checkout.component.ts
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.spec.ts
  src/app/components/log-in/log-in.component.html
  src/app/components/log-in/log-in.component.spec.ts
  src/app/components/log-in/log-in.component.ts
  src/app/components/my-profile/profile.component.html
  src/app/components/my-profile/profile.component.scss
  src/app/components/my-profile/profile.component.spec.ts
  src/app/components/my-profile/profile.component.ts
  src/app/components/order-details/order-details.component.html
  src/app/components/order-details/order-details.component.scss
  src/app/components/order-details/order-details.component.ts
  src/app/components/orders/orders.component.html
  src/app/components/orders/orders.component.scss
  src/app/components/orders/orders.component.spec.ts
  src/app/components/orders/orders.component.ts
Labels: enhancement

#152 Home page materials added to cards
  src/app/components/home/home.component.ts
  src/assets/images/86-Asian-Paint-full.jpeg
  src/assets/images/bricks.jpeg
Labels: enhancement

#156 Feature/product search
  src/app/app-routing.module.ts
  src/app/components/card/card.component.html
  src/app/components/card/card.component.scss
  src/app/components/card/home-card/home-card.component.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/app/components/images/images.component.html
  src/app/components/images/images.component.ts
  src/app/components/leftsection/leftsection.component.html
  src/app/components/leftsection/leftsection.component.spec.ts
  src/app/components/leftsection/leftsection.component.ts
  src/app/components/product-details/product-details.component.ts
  src/app/components/product-results/product-results.component.spec.ts
  src/app/components/product-results/product-results.component.ts
  src/app/components/topnav/topnav.component.html
  src/app/components/topnav/topnav.component.ts
  src/app/services/products/products.service.ts
  src/app/services/products/query.interface.ts
  src/app/shared-services/search-item/search-item.services.ts
  src/app/utils/common.ts
Labels: bug, enhancement

#157 Feature/vat changes
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.scss
  src/app/components/cart/cart.component.ts
  src/app/components/checkout/checkout.component.html
  src/app/components/checkout/checkout.component.scss
  src/app/components/checkout/checkout.component.ts
  src/app/components/order-details/order-details.component.html
  src/app/components/order-details/order-details.component.scss
  src/app/components/order-details/order-details.component.ts
  src/app/components/orders/orders.component.html
  src/app/components/orders/orders.component.scss
  src/app/components/orders/orders.component.spec.ts
  src/app/components/orders/orders.component.ts
Labels: enhancement

#158 Bug/ui issues
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/leftsection/leftsection.component.ts
  src/app/components/product-details/product-details.component.ts
  src/app/components/product-results/product-results.component.html
  src/app/components/range-slider/range-slider.component.html
  src/app/components/range-slider/range-slider.component.scss
Labels: bug

#159 removed default value
  src/app/components/product-details/product-details.component.ts
Labels: bug

#166 Added checkProductReview call to the service
  src/app/authmock/authmock.component.html
  src/app/authmock/authmock.component.ts
  src/app/services/ratings/ratings.service.ts
Labels: enhancement

#167 Feature/customer reviews
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/authmock/authmock.component.ts
  src/app/common/icons/icons.component.html
  src/app/components/card/card.component.html
  src/app/components/create-review/create-review.component.html
  src/app/components/create-review/create-review.component.scss
  src/app/components/create-review/create-review.component.spec.ts
  src/app/components/create-review/create-review.component.ts
  src/app/components/credits/credits.component.spec.ts
  src/app/components/customer-reviews/customer-reviews.component.html
  src/app/components/customer-reviews/customer-reviews.component.scss
  src/app/components/customer-reviews/customer-reviews.component.spec.ts
  src/app/components/customer-reviews/customer-reviews.component.ts
  src/app/components/edit-review/edit-review.component.html
  src/app/components/edit-review/edit-review.component.scss
  src/app/components/edit-review/edit-review.component.spec.ts
  src/app/components/edit-review/edit-review.component.ts
  src/app/components/leftsection/leftsection.component.html
  src/app/components/log-in/log-in.component.html
  src/app/components/log-in/log-in.component.ts
  src/app/components/my-profile/profile.component.ts
  src/app/components/orders/orders.component.html
  src/app/components/orders/orders.component.scss
  src/app/components/orders/orders.component.ts
  src/app/components/product-details/product-details.component.html
  src/app/components/product-details/product-details.component.scss
  src/app/components/product-details/product-details.component.spec.ts
  src/app/components/product-details/product-details.component.ts
  src/app/components/product-results/product-results.component.scss
  src/app/components/product-reviews/product-reviews.component.html
  src/app/components/product-reviews/product-reviews.component.scss
  src/app/components/product-reviews/product-reviews.component.spec.ts
  src/app/components/product-reviews/product-reviews.component.ts
  src/app/components/rating-bar/rating-bar.component.html
  src/app/components/rating-bar/rating-bar.component.ts
  src/app/components/rating/rating.component.html
  src/app/components/rating/rating.component.ts
  src/app/services/orders/orders.mock.data.ts
  src/app/services/orders/orders.mock.service.ts
  src/app/services/ratings/ratings.mock.data.ts
  src/app/services/ratings/ratings.mock.service.ts
  src/app/services/ratings/ratings.service.ts
  src/app/utils/constants.ts
Labels: enhancement

#168 #164 Fixed sort by and filter by issues
  src/app/components/leftsection/leftsection.component.ts
  src/app/utils/common.ts
Labels: bug

#169 #111 Sort buy icons in products page
  src/app/components/leftsection/leftsection.component.html
  src/app/components/leftsection/leftsection.component.ts
Labels: enhancement

#170 Fixed subcategory search issue
  src/app/components/leftsection/leftsection.component.ts
Labels: bug

#172 Feature/guest checkout
  src/app/components/guest-checkout/guest-checkout.component.html
  src/app/components/guest-checkout/guest-checkout.component.scss
  src/app/components/guest-checkout/guest-checkout.component.ts
  src/app/components/order-details/order-details.component.scss
Labels: enhancement
