Repository virtuelabs-io/rapido-web, pull requests merged in 2019-08, with the labels that each got.

#30 Feature/deployment
  azure-pipelines.yml
  package-lock.json
  src/app/footer/footer.component.html
  src/app/footer/footer.component.scss
  src/app/footer/footer.component.ts
Labels: enhancement

#31 Bug/fixes
  src/app/card/carousel-scroll/carousel-scroll.component.html
  src/app/card/carousel-scroll/carousel-scroll.component.scss
  src/app/card/carousel-scroll/carousel-scroll.component.ts
  src/app/card/carousel/carousel.component.html
  src/app/card/carousel/carousel.component.scss
  src/app/card/carousel/carousel.component.ts
  src/app/card/home-card/home-card.component.html
  src/app/card/home-card/home-card.component.scss
  src/app/cart/cart.component.html
  src/app/cart/cart.component.scss
  src/app/cart/cart.component.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.scss
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.scss
  src/app/orders/orders.component.ts
  src/app/topnav/topnav.component.scss
  src/app/utils/constants.ts
  src/styles.scss
Labels: bug

#32 [Feature - Enhancement] : Implemented Cart Cont feature
  src/app/app-routing.module.ts
  src/app/log-in/log-in.component.ts
  src/app/product-details/product-details.component.html
  src/app/product-details/product-details.component.ts
  src/app/services/commons/rapido-http.service.ts
  src/app/shared-services/cart-state/cart-state.service.spec.ts
  src/app/shared-services/cart-state/cart-state.service.ts
  src/app/topnav/topnav.component.html
  src/app/topnav/topnav.component.spec.ts
  src/app/topnav/topnav.component.ts
Labels: enhancement

#68 Orders issue
  README.md
  src/app/order-details/order-details.component.scss
Labels: bug

#69 cancel button was appearing even when the order was cancelled
  src/app/my-profile/profile.component.html
  src/app/my-profile/profile.component.scss
  src/app/my-profile/profile.component.spec.ts
  src/app/my-profile/profile.component.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.scss
  src/app/orders/orders.component.ts
Labels: bug

#70 Updating cart count upon delete and save later
  src/app/cart/cart.component.html
  src/app/cart/cart.component.ts
  src/app/common/icons/icons.component.html
  src/app/log-in/log-in.component.spec.ts
  src/app/log-in/log-in.component.ts
  src/app/product-details/product-details.component.html
  src/app/product-details/product-details.component.scss
  src/app/product-details/product-details.component.spec.ts
  src/app/product-details/product-details.component.ts
  src/app/shared-services/cart-state/cart-state.service.spec.ts
  src/app/shared-services/cart-state/cart-state.service.ts
  src/app/topnav/topnav.component.html
  src/app/topnav/topnav.component.scss
  src/app/topnav/topnav.component.ts
  src/app/utils/constants.ts
Labels: bug

#72 Bug/carousel component
  azure-pipelines.yml
  src/app/app.component.html
  src/app/app.component.ts
  src/app/card/carousel-scroll/carousel-scroll.component.html
  src/app/card/carousel-scroll/carousel-scroll.component.scss
  src/app/card/carousel-scroll/carousel-scroll.component.ts
  src/app/card/carousel/carousel.component.html
  src/app/card/carousel/carousel.component.scss
  src/app/card/carousel/carousel.component.spec.ts
  src/app/card/carousel/carousel.component.ts
  src/app/card/home-card/home-card.component.html
  src/app/card/home-card/home-card.component.scss
  src/app/card/home-card/home-card.component.spec.ts
  src/app/card/home-card/home-card.component.ts
  src/app/checkout/checkout.component.html
  src/app/footer/footer.component.html
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/topnav/topnav.component.html
  src/app/topnav/topnav.component.scss
  src/assets/images/Watches.jpeg
  src/styles.scss
Labels: bug

#76 Title alignment issues
  src/app/address/address.component.scss
  src/app/company-details/company-details.component.html
  src/app/company-details/company-details.component.scss
Labels: bug

#80 Bug/profile related
  azure-pipelines.yml
  package-lock.json
  src/app/account-info/account-info.component.html
  src/app/account-info/account-info.component.scss
  src/app/account-info/account-info.component.ts
  src/app/card/carousel-scroll/carousel-scroll.component.scss
Labels: bug

#81 Bug/company details
  src/app/account-info/account-info.component.ts
  src/app/add-company-details/add-company-details.component.html
  src/app/add-company-details/add-company-details.component.scss
  src/app/add-company-details/add-company-details.component.spec.ts
  src/app/add-company-details/add-company-details.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/company-details/company-details.component.html
  src/app/company-details/company-details.component.scss
  src/app/company-details/company-details.component.spec.ts
  src/app/company-details/company-details.component.ts
  src/app/edit-company-details/edit-company-details.component.html
  src/app/edit-company-details/edit-company-details.component.scss
  src/app/edit-company-details/edit-company-details.component.spec.ts
  src/app/edit-company-details/edit-company-details.component.ts
  src/app/home/home.component.ts
  src/app/utils/constants.ts
Labels: bug

#82 This PR contains Addition of social media icons
  src/app/card/card.component.html
  src/app/components/common/pill-badge/pill-badge.component.html
  src/app/components/common/pill-badge/pill-badge.component.scss
  src/app/footer/footer.component.html
  src/app/images/images.component.html
  src/app/product-details/product-details.component.html
  src/app/product-results/product-results.component.html
  src/app/topnav/topnav.component.html
  src/app/topnav/topnav.component.scss
  src/app/topnav/topnav.component.ts
Labels: bug

#83 Feature/help page
  src/app/address/address.component.ts
  src/app/app-routing.module.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.ts
  src/app/my-profile/profile.component.html
  src/app/my-profile/profile.component.scss
  src/app/my-profile/profile.component.spec.ts
  src/app/my-profile/profile.component.ts
  src/app/topnav/topnav.component.html
  src/app/topnav/topnav.component.ts
Labels: bug

#84 Feature - product hierarchy
  src/app/app.module.ts
  src/app/common/icons/icons.component.html
  src/app/leftsection/leftsection.component.html
  src/app/leftsection/leftsection.component.spec.ts
  src/app/leftsection/leftsection.component.ts
  src/app/product-details/product-details.component.html
  src/app/product-results/product-results.component.html
  src/app/topnav/topnav.component.html
  src/index.html
Labels: bug, enhancement

#85 footer issues
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/cart/cart.component.html
  src/app/common/icons/icons.component.html
  src/app/footer/footer.component.html
  src/styles.scss
Labels: bug

#86 Route to log in page when user not logged in
  src/app/account-info/account-info.component.ts
  src/app/address/address.component.spec.ts
  src/app/address/address.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/authmock/authmock.component.html
  src/app/authmock/authmock.component.ts
  src/app/card/carousel/carousel.component.ts
  src/app/cart/cart.component.spec.ts
  src/app/cart/cart.component.ts
  src/app/common/button/button.component.html
  src/app/common/button/button.component.scss
  src/app/common/button/button.component.spec.ts
  src/app/common/button/button.component.ts
  src/app/company-details/company-details.component.spec.ts
  src/app/company-details/company-details.component.ts
  src/app/edit-address/edit-address.component.spec.ts
  src/app/edit-address/edit-address.component.ts
  src/app/footer/footer.component.ts
  src/app/log-in/log-in.component.spec.ts
  src/app/log-in/log-in.component.ts
  src/app/order-details/order-details.component.spec.ts
  src/app/order-details/order-details.component.ts
  src/app/orders/orders.component.spec.ts
  src/app/orders/orders.component.ts
  src/app/product-details/product-details.component.spec.ts
  src/app/product-details/product-details.component.ts
  src/app/services/commons/rapido-http.service.ts
  src/app/services/customer/address-details.mock.data.ts
  src/app/services/customer/address-details.mock.service.ts
  src/app/services/customer/address-details.service.ts
  src/app/topnav/topnav.component.spec.ts
Labels: bug

#87 Bug/cart component
  src/app/cart/cart.component.html
  src/app/cart/cart.component.scss
  src/app/cart/cart.component.ts
Labels: bug

#88 career page
  src/app/app-routing.module.ts
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/components/career-page/career-page.component.html
  src/app/components/career-page/career-page.component.scss
  src/app/components/career-page/career-page.component.spec.ts
  src/app/components/career-page/career-page.component.ts
  src/app/footer/footer.component.html
  src/app/leftsection/leftsection.component.html
  src/app/leftsection/leftsection.component.ts
  src/app/product-results/product-results.component.ts
  src/app/utils/config.ts
Labels: enhancement

#92 Added icon for terms of service and privacy policy and footer name ch…
  src/app/common/icons/icons.component.html
  src/app/footer/footer.component.html
  src/app/privacy-policy/privacy-policy.component.html
  src/app/privacy-policy/privacy-policy.component.scss
  src/app/terms-conditions/terms-conditions.component.html
  src/app/terms-conditions/terms-conditions.component.scss
Labels: bug

#94 Press release component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/footer/footer.component.html
  src/app/press-release/press-release.component.html
  src/app/press-release/press-release.component.scss
  src/app/press-release/press-release.component.spec.ts
  src/app/press-release/press-release.component.ts
Labels: enhancement

#93 fixed loader issue in cart page
  src/app/cart/cart.component.ts
  src/app/shared-services/login-state/login-state.service.ts
Labels: bug

#100 Feature/credits
  src/app/app-routing.module.ts
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/cart/cart.component.ts
  src/app/components/credits/credits.component.html
  src/app/components/credits/credits.component.scss
  src/app/components/credits/credits.component.spec.ts
  src/app/components/credits/credits.component.ts
  src/app/footer/footer.component.html
  src/app/leftsection/leftsection.component.ts
Labels: bug, enhancement

#122 Added generic mathod to accept 1-9 digits for price filter input
  src/app/components/card/card.component.html
  src/app/components/card/carousel-scroll/carousel-scroll.component.html
  src/app/components/card/carousel/carousel.component.html
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.ts
  src/app/components/product-details/product-details.component.html
  src/app/components/product-details/product-details.component.ts
  src/app/components/range-slider/range-slider.component.html
  src/app/components/range-slider/range-slider.component.ts
  src/app/utils/common.ts
Labels: bug

#123 Bug/home component
  src/app/components/card/carousel-scroll/carousel-scroll.component.scss
  src/app/components/card/carousel/carousel.component.scss
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/footer/footer.component.ts
  src/app/components/orders/orders.component.ts
  src/app/components/topnav/topnav.component.ts
Labels: bug

#124 minor fix
  package-lock.json
  src/app/New Microsoft Access Database.accdb
  src/app/app.component.html
  src/app/app.component.scss
  src/app/common/icons/icons.component.html
  src/app/components/card/card.component.scss
  src/app/components/card/carousel/carousel.component.html
  src/app/components/card/carousel/carousel.component.scss
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/app/components/home/home.component.scss
  src/app/components/log-in/log-in.component.html
  src/app/components/my-profile/profile.component.html
  src/app/components/my-profile/profile.component.scss
  src/styles.scss
Labels: bug

#125 Bug/press and address
  src/app/common/icons/icons.component.html
  src/app/components/address/address.component.html
  src/app/components/address/address.component.scss
  src/app/components/footer/footer.component.scss
  src/app/components/press-release/press-release.component.html
  src/app/components/press-release/press-release.component.scss
  src/app/components/topnav/topnav.component.html
  src/app/components/topnav/topnav.component.scss
Labels: bug

#126 removed amount and currency
  src/app/components/checkout/checkout.component.ts
  src/app/components/topnav/topnav.component.ts
  src/app/services/payment/charge.ts
Labels: bug

#127 Bug/add icons
  src/app/common/icons/icons.component.html
  src/app/components/add-address/add-address.component.html
  src/app/components/add-address/add-address.component.scss
  src/app/components/address/address.component.html
  src/app/components/address/address.component.scss
  src/app/components/cart/cart.component.html
  src/app/components/cart/cart.component.scss
  src/app/components/checkout/checkout.component.html
  src/app/components/checkout/checkout.component.scss
  src/app/components/checkout/checkout.component.ts
  src/app/components/company-details/company-details.component.html
  src/app/components/company-details/company-details.component.scss
  src/app/components/edit-address/edit-address.component.html
  src/app/components/edit-address/edit-address.component.scss
  src/app/components/my-profile/profile.component.html
  src/app/components/my-profile/profile.component.scss
  src/app/components/order-details/order-details.component.html
  src/app/components/order-details/order-details.component.scss
Labels: bug, enhancement

#132 Bug/loader enable
  src/app/components/address/address.component.html
  src/app/components/address/address.component.ts
  src/app/components/checkout/checkout.component.ts
  src/app/components/company-details/company-details.component.ts
  src/app/components/edit-address/edit-address.component.html
  src/app/components/edit-address/edit-address.component.spec.ts
  src/app/components/edit-address/edit-address.component.ts
  src/app/components/order-details/order-details.component.ts
  src/app/components/orders/orders.component.ts
Labels: bug

#133 #101
  src/app/common/icons/icons.component.html
  src/app/components/product-details/product-details.component.html
  src/app/components/product-details/product-details.component.scss
  src/app/components/product-results/product-results.component.html
  src/app/components/product-results/product-results.component.scss
Labels: bug

#137 Bug/careers page
  src/app/components/card/card.component.scss
  src/app/components/career-page/career-page.component.html
  src/app/components/career-page/career-page.component.scss
  src/app/components/checkout/checkout.component.ts
  src/app/components/leftsection/leftsection.component.scss
  src/app/components/rating/rating.component.scss
  src/assets/scss/custom-bootstrap-variables.scss
Labels: bug

#136 handling update cart count gracefully
  src/app/components/card/carousel/carousel.component.spec.ts
  src/app/components/card/carousel/carousel.component.ts
  src/app/components/order-details/order-details.component.ts
Labels: bug

#140 Bug/company details in order summary
  src/app/components/cart/cart.component.ts
  src/app/components/checkout/checkout.component.html
  src/app/components/checkout/checkout.component.ts
  src/app/components/company-details/company-details.component.ts
  src/app/components/order-details/order-details.component.html
  src/app/components/order-details/order-details.component.scss
  src/app/components/order-details/order-details.component.ts
Labels: bug

#141 Feature/side nav
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/components/card/carousel-scroll/carousel-scroll.component.html
  src/app/components/card/carousel-scroll/carousel-scroll.component.scss
  src/app/components/home/home.component.html
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
  src/app/components/nav/nav.component.html
  src/app/components/nav/nav.component.scss
  src/app/components/nav/nav.component.spec.ts
  src/app/components/nav/nav.component.ts
  src/app/components/topnav/topnav.component.html
  src/app/components/topnav/topnav.component.spec.ts
  src/app/components/topnav/topnav.component.ts
  src/assets/images/Rapido1.jpeg
  src/assets/images/Watches.jpeg
  src/assets/images/fashion.jpg
  src/assets/images/furnitures.jpg
  src/assets/images/laptops.jpeg
  src/assets/images/sale.jpg
  src/assets/images/sunglass.jpg
  src/assets/images/wallets.jpg
  src/assets/images/watches.jpg
Labels: enhancement

#142 scroll fix
  src/app/components/nav/nav.component.html
Labels: bug

#143 Feature/ratings service
  src/app/authmock/authmock.component.html
  src/app/authmock/authmock.component.ts
  src/app/services/orders/orders.service.ts
  src/app/services/ratings/rating.ts
  src/app/services/ratings/ratings.service.spec.ts
  src/app/services/ratings/ratings.service.ts
  src/app/utils/constants.ts
Labels: enhancement

#144 Vat and delivery cost
  src/app/authmock/authmock.component.html
  src/app/authmock/authmock.component.ts
  src/app/services/orders/order.ts
  src/app/services/orders/orders.service.ts
Labels: enhancement
